defmodule Darkly.APIError do
  @moduledoc """
  Errors generated by Launch Darkly API
  """
  defexception [:message, :code]
  @impl true
  def exception(args) do
    Kernel.struct!(__MODULE__, args)
  end

  @impl true
  def message(%__MODULE__{code: code, message: message}), do: "#{inspect(message)} - #{code}"
end
